name: Build Cryptomator Premium IPA

on:
  workflow_dispatch: 

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-14 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Inject Dummy CloudAccessSecrets
        run: |
          export BOX_CLIENT_ID="dummy_key"
          export BOX_CLIENT_SECRET="dummy_key"
          export DROPBOX_APP_KEY="dummy_key"
          export GOOGLE_DRIVE_CLIENT_ID="dummy_key"
          export GOOGLE_DRIVE_REDIRECT_URL_SCHEME="dummy_key"
          export MICROSOFT_GRAPH_CLIENT_ID="dummy_key"
          export MICROSOFT_GRAPH_REDIRECT_URI_SCHEME="dummy_key"
          export PCLOUD_APP_KEY="dummy_key"
          
          cd fastlane
          ./scripts/create-cloud-access-secrets.sh

      - name: Build and Archive
        run: |
          set -o pipefail
          xcodebuild clean archive \
            -scheme Cryptomator \
            -configuration Release \
            -archivePath $PWD/build/Cryptomator.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            SWIFT_ACTIVE_COMPILATION_CONDITIONS="\$(inherited) ALWAYS_PREMIUM" | xcbeautify

      - name: Package IPA
        run: |
          mkdir -p Payload
          mv build/Cryptomator.xcarchive/Products/Applications/Cryptomator.app Payload/
          zip -qr9 Cryptomator-Premium.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cryptomator-Premium
          path: Cryptomator-Premium.ipa
